### ISSUE TITLE
Conformal Point Inversion

### ISSUE THREAD

**Issue by CaseySanchez** [laffernandes/gatl#31]
The program:

```
#include <gatl/ga3c.hpp>

using namespace ga3c;

template <typename CoefficientType, typename Expression>
constexpr auto make_conformal_point(clifford_expression<CoefficientType, Expression> const &euclidean_point)
{
    return euclidean_point + no + 0.5 * euclidean_point * euclidean_point * ni;
}

int main(int argc, char **argv)
{    
    std::cout << make_conformal_point(1.0 * e1 + 1.0 * e2 + 1.0 * e3) << std::endl;
    std::cout << inv(make_conformal_point(1.0 * e1 + 1.0 * e2 + 1.0 * e3)) << std::endl;

    return 0;
}
```

The output:
```
1 * <e1> + 1 * <e2> + 1 * <e3> + <1> * <no> + 1.5 * <ni> + 0 * <e1^e2^ni> + 0 * <e1^e3^ni> + 0 * <e2^e3^ni>
inf * <e1> + inf * <e2> + inf * <e3> + inf * <no> + inf * <ni> + (nan) * <e1^e2^ni> + (nan) * <e1^e3^ni> + (nan) * <e2^e3^ni>
```

The conformal point represented with bases `e4` and `e5` is expanded as `1.0 * e1 + 1.0 * e2 + 1.0 * e3 + 1.0 * e4 + 2.0 * e5`. Evaluating the inversion by hand results in all bivector components cancelling and the scalar components summing to zero `1 + 1 + 1 + 1 + 4(-1) = 0`, such that the result of the inversion is `0`.

Regards,
Casey

**Comment by laffernandes** [comment]
The result is correct. The vectors encoding finite points in the Conformal Model of Geometry are null vectors. Therefore, those vectors are not invertible, leading to division by zero in the evaluation of the `inv` function.

The grade-3 components in the result are also correct, as the implementation did not use lazy context to allow the algebraic simplification of operations. See (this example)[https://github.com/laffernandes/gatl/blob/master/cpp/tools/example/concepts/lazy_evaluation.cpp] and the (paper)[https://doi.org/10.1007/978-3-030-74486-1_6] for in-deep discussion.

Instead of declaring your own `make_conformal_point` function, please consider using the `point` function from GATL (see the (documentation)[https://github.com/laffernandes/gatl#conformal]).

**Comment by CaseySanchez** [comment]
> The result is correct. The vectors encoding finite points in the Conformal Model of Geometry are null vectors. Therefore, those vectors are not invertible, leading to division by zero in the evaluation of the `inv` function.
> 
> The grade-3 components in the result are also correct, as the implementation did not use lazy context to allow the algebraic simplification of operations. See (this example)[https://github.com/laffernandes/gatl/blob/master/cpp/tools/example/concepts/lazy_evaluation.cpp] and the (paper)[https://doi.org/10.1007/978-3-030-74486-1_6] for in-deep discussion.
> 
> Instead of declaring your own `make_conformal_point` function, please consider using the `point` function from GATL (see the (documentation)[https://github.com/laffernandes/gatl#conformal]).

You are absolutely correct, it is the denominator that evaluates to `0`, not the complete inversion. I apologize for the confusion.

Thank you for the information regarding `point`. Do you think it would be wise to rename the method to `make_point` so as to not cause naming conflicts should users desire to create a variable named `point`? For example:
```
auto const point = make_point(1.0, 1.0, 1.0);

std::cout << point << std::endl;
std::cout << inv(point) << std::endl;
```

**Comment by laffernandes** [comment]
Thank you for the suggestion, but I will keep the name of the function. You can use `auto const point = ga3c::point(value1, value2, value3);` to set the `point` variable while name ambiguity is resolved by indicating the namespace where the function was defined.
